apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:f1218ca1b1bf101a179e0b171ee552e18074c8be1d65d97727e45f8093af1c3d
        name: container-image
        resources: {}
status: {}
