apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:fa34a33c62f02dee1cb84dc1fd5e79a1cbb9b06f5ac671173f88e1835ae2e705
        name: container-image
        resources: {}
status: {}
