apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:eba44dcb61fcf111e0c997d6c122249ab2bb2463655616526b24edff75726d73
        name: container-image
        resources: {}
status: {}
