apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:43c12c811ff11f33aceef3d0064537fc5726560bbcb6a3d1854c338fb2186fae
        name: container-image
        resources: {}
status: {}
