apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:a4107b5be79437a3287945d74c917c42d7b786a72c9a56d79f68d086f28130dd
        name: container-image
        resources: {}
status: {}
