apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fedora-bootc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:383fd6ce6a1fed0ec2542d296557413aeb9ea78ac0f39bbe1dbee07672b70a7d
        name: container-image
        resources: {}
status: {}
