apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fedora-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fedora-bootc
    app.kubernetes.io/part-of: fedora-bootc
  name: fedora-bootc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fedora-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fedora-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:0c2caa90b60c5dad60bd9d0f0a2596b3fcc51ecf44fc5bcc6070515a3451696e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
