apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fedora-bootc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fedora-bootc
    app.kubernetes.io/part-of: fedora-bootc
  name: fedora-bootc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: fedora-bootc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fedora-bootc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/centos-bootc-tenant/fedora-bootc/fedora-bootc@sha256:6ad45426dd0d0f2aa00af840ddebe20db397b501fdd7b552d8ddb83a5b1df155
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
